<?php
/**
 * @file
 * The domains and their corresponding ACS ids need to be communicated to the
 * IDM/SSO team.
 */

$main_domain = array(
  'publisher7.com' => 'publisher7',
);

$domains = array(
  'local.install.publisher7.com' => 'pub-local',
  'qa.publisher7.com' => 'pub-qa',
  'qa1.publisher7.com' => 'pub-qa1',
  'qa2.publisher7.com' => 'pub-qa2',
  'qa3.publisher7.com' => 'pub-qa3',
  'qa4.publisher7.com' => 'pub-qa4',
  'qa5.publisher7.com' => 'pub-qa5',
  'stage.publisher7.com' => 'pub-stage',
  'acc.publisher7.com' => 'pub-acc',
  'prod.publisher7.com' => 'pub-prod',
  'publisher.nbcuni.com' => 'pub-pub',
  'demo.publisher7.com' => 'pub-demo',
  'dev.demo.publisher7.com' => 'pub-demodev',
  'stage.demo.publisher7.com' => 'pub-demostage',
  'dbtv.nbcuni.com' => 'pub-dbtv',
  'demo.qa.dbtv.publisher7.com' => 'pub-dbtvqademo',
  'install.hotfix-qa.nbcupublisher7.publisher7.com' => 'pub-hotfixqainstall',
  'install.hotfix-stage.nbcupublisher7.publisher7.com' => 'pub-hotfixstageinstall',
);
