<?php
/**
 * @file
 * Code for the FYC USA Build feature.
 */

include_once 'fycusa_build.features.inc';

/**
 * Vocabulary for templates of new fyc show.
 */
define('FYC_MENU_ITEMS_VOCABULARY', 'menu_items');

/**
 * Implements hook_module_implements_alter().
 */
function fycusa_build_module_implements_alter(&$implementations, $hook) {
    if ($hook == 'taxonomy_term_insert') {
        // Move hook to the end of the list.
        $group = $implementations['fycusa_build'];
        unset($implementations['fycusa_build']);
        $implementations['fycusa_build'] = $group;
    }
}
