<?php

/*
 * This file is autogenerated by the Publisher7 build toolchain.
 *
 * It can be regenerated at any time by running `bunle exec rake generate_sites_file`.
 */

$multisites = array(
  'install' => 'install.publisher7.com',
  'update' => 'update.publisher7.com',
  'fycusa' => 'fyc.usanetwork.com',
  'fycsyfy' => 'fyc.syfy.com',
  'usa' => 'press.usanetwork.com',
  'syfy' => 'press.syfy.com'
);

$envs = array('qa', 'qa1', 'qa2', 'qa3', 'qa4', 'qa5', 'tmp', 'stage', 'prod');

foreach ($multisites as $sitename => $domain) {
  foreach ($envs as $env) {
    $sites["$sitename.$env.nbcupublisher7.publisher7.com"] = $sitename;
    $sites[$sitename . $env . '.apps.nbcuni.com'] = $sitename;
    $sites['usa' . $sitename . $env . '.apps.nbcuni.com'] = $sitename;
    $sites[$sitename . 'pr' . $env . '.apps.nbcuni.com'] = $sitename;
    $sites[$sitename . 'press' . $env . '.apps.nbcuni.com'] = $sitename;
  }
  $sites['local.' . $sitename] = $sitename;
  $sites['loc.' . $sitename . '.com'] = $sitename;
  $sites['local.' . $sitename . '.com'] = $sitename;
  $sites[$sitename . '.local'] = $sitename;
  $sites['local.publisher.' . $sitename] = $sitename;
  $sites['dev-' . $domain] = $sitename;
  $sites['publisher.' . $sitename . '.local'] = $sitename;
  $sites[$sitename] = $sitename;

  // $domain may have been empty; if so, do not add it.
  if (!empty($domain)) {
    $sites[$domain] = $sitename;
    $sites['local.' . $domain] = $sitename;
  }
}

// Allow users to define their own $sites aliases with a sites.local.php, if desired.
$local_sites = __DIR__ . '/sites.local.php';
if (file_exists($local_sites)) {
  include($local_sites);
}
